using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WFC_ORION.DAL
{
    public class TercerosBD
    {
		public static SqlDataReader GetTerceros(DBAccess ObjDB, int TRCODTER)
		{
			StringBuilder sSql = new StringBuilder();

			try
			{
				sSql.AppendLine("SELECT * FROM TERCEROS WITH(NOLOCK) WHERE TRCODTER = @p0 ");

				return ObjDB.ExecuteReader(sSql.ToString(), TRCODTER);
			}
			catch (Exception ex)
			{
				throw ex;
			}
			finally
			{
				sSql = null;
			}
		}

		public static SqlDataReader GetTercerosMultintegralPH(DBAccess ObjDB, string inFiltro)
		{
			StringBuilder sSql = new StringBuilder();

			try
			{
				sSql.AppendLine("SELECT  TERCEROS.*,");
				sSql.AppendLine("(SELECT COUNT(*) FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER) POTENCIAL,");
				sSql.AppendLine("(SELECT COUNT(TB_INSTALACION.IT_CODIGO) FROM TB_INSTALACION WITH(NOLOCK) WHERE PH_CODIGO IN(SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER)) INSTALADOS,");

				sSql.AppendLine("(SELECT COUNT(TB_PROPIEDAHORIZONTAL.PH_CODIGO) FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER");
				sSql.AppendLine("AND PH_CODIGO NOT IN (SELECT PH_CODIGO FROM TB_COMERCIAL WITH(NOLOCK) WHERE PH_CODIGO IN (SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER))");
				sSql.AppendLine("AND PH_CODIGO NOT IN (SELECT PH_CODIGO FROM TB_DESISTALACION WITH(NOLOCK) WHERE PH_CODIGO IN (SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER))");
				sSql.AppendLine("AND PH_CODIGO NOT IN (SELECT PH_CODIGO FROM TB_CORRESPONDENCIADTOUT WITH(NOLOCK) WHERE PH_CODIGO IN (SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER))");
				sSql.AppendLine("AND PH_CODIGO NOT IN (SELECT PH_CODIGO FROM TB_TICKETHD WHERE TB_TICKETHD.PH_CODIGO IN (SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER) AND TK_TIPO = '0' AND TK_ESTADO='AC' )");
				sSql.AppendLine("AND PH_CODIGO NOT IN(SELECT PH_CODIGO FROM TB_HURTOS WITH(NOLOCK) WHERE TB_HURTOS.PH_CODIGO IN (SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER))");
				sSql.AppendLine(") PEN_COMERCIALIZAR,");

				sSql.AppendLine("(SELECT COUNT(TB_COMERCIAL.CO_CODIGO) FROM TB_COMERCIAL WITH(NOLOCK) WHERE PH_CODIGO IN(SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER");
				sSql.AppendLine("AND PH_CODIGO NOT IN(SELECT PH_CODIGO FROM TB_DESISTALACION WITH(NOLOCK) WHERE PH_CODIGO IN(SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER)))");
				sSql.AppendLine("AND PH_CODIGO NOT IN(SELECT TB_CORRESPONDENCIADTIN.PH_CODIGO FROM TB_CORRESPONDENCIADTIN WITH(NOLOCK) WHERE PH_CODIGO IN(SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER))");
				sSql.AppendLine("AND PH_CODIGO NOT IN(SELECT TB_CORRESPONDENCIADTOUT.PH_CODIGO FROM TB_CORRESPONDENCIADTOUT WITH(NOLOCK) WHERE PH_CODIGO IN (SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER))");
				sSql.AppendLine("AND PH_CODIGO NOT IN(SELECT PH_CODIGO FROM TB_TICKETHD WHERE TB_TICKETHD.PH_CODIGO IN (SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER) AND TK_TIPO = '0' AND TK_ESTADO = 'AC' )");
				sSql.AppendLine(") PEN_RADOFF,");

				sSql.AppendLine("(SELECT COUNT(TB_DESISTALACION.DI_CODIGO) FROM TB_DESISTALACION WITH(NOLOCK) WHERE PH_CODIGO IN(SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER)) DESINSTALADOS,");
				sSql.AppendLine("(SELECT COUNT(TB_CORRESPONDENCIADTOUT.PH_CODIGO) FROM TB_CORRESPONDENCIADTOUT WITH(NOLOCK) WHERE PH_CODIGO IN(SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER)");
				sSql.AppendLine("AND PH_CODIGO NOT IN(SELECT PH_CODIGO FROM TB_DESISTALACION WITH(NOLOCK) WHERE PH_CODIGO IN(SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER))");
				sSql.AppendLine(") VANTI,");

				sSql.AppendLine("(SELECT COUNT(DISTINCT TB_CORRESPONDENCIADTIN.PH_CODIGO) FROM TB_CORRESPONDENCIADTIN WITH(NOLOCK) WHERE PH_CODIGO IN(SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER)");
				sSql.AppendLine("AND PH_CODIGO NOT IN(SELECT PH_CODIGO FROM TB_DESISTALACION WITH(NOLOCK) WHERE PH_CODIGO IN (SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER))");
				sSql.AppendLine("AND PH_CODIGO NOT IN(SELECT PH_CODIGO FROM TB_CORRESPONDENCIADTOUT WITH(NOLOCK) WHERE PH_CODIGO IN (SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER))");
				sSql.AppendLine("AND PH_CODIGO NOT IN(SELECT PH_CODIGO FROM TB_TICKETHD WHERE TB_TICKETHD.PH_CODIGO IN (SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER) AND TK_TIPO = '0' AND TK_ESTADO = 'AC' )");
				sSql.AppendLine(") OFICINA,");

				sSql.AppendLine("(SELECT COUNT(PH_CODIGO) FROM TB_TICKETHD WITH(NOLOCK) WHERE TB_TICKETHD.PH_CODIGO IN(SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER) AND TK_TIPO = '0' AND TK_ESTADO = 'AC'");
				sSql.AppendLine("AND PH_CODIGO NOT IN(SELECT PH_CODIGO FROM TB_DESISTALACION WITH(NOLOCK) WHERE PH_CODIGO IN (SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER))");
				sSql.AppendLine(") P_DESMONTE,");

				sSql.AppendLine("(SELECT COUNT(PH_CODIGO) FROM TB_HURTOS WITH(NOLOCK) WHERE PH_CODIGO IN (SELECT PH_CODIGO FROM TB_PROPIEDAHORIZONTAL WITH(NOLOCK) WHERE TB_PROPIEDAHORIZONTAL.TRCODTER = TERCEROS.TRCODTER)) HURTADOS");

				sSql.AppendLine("FROM TERCEROS WITH(NOLOCK)");
				sSql.AppendLine("WHERE 1=1 " + inFiltro);

				return ObjDB.ExecuteReader(sSql.ToString(), inFiltro);
			}
			catch (Exception ex)
			{
				throw ex;
			}
			finally
			{
				sSql = null;
			}
		}

		public static int ExisteTercero(DBAccess ObjDB, string TRCODNIT)
		{
			StringBuilder sSql = new StringBuilder();
			try
			{
				sSql.AppendLine("SELECT COUNT(*) FROM TERCEROS WITH(NOLOCK) WHERE TRCODNIT =@p0");

				return Convert.ToInt32(ObjDB.ExecuteScalar(sSql.ToString(), TRCODNIT));
			}
			catch (Exception ex)
			{
				throw ex;
			}
			finally
			{
				sSql = null;
			}
		}
		public static int getCodTer(DBAccess ObjDB, string TRCODNIT)
		{
			StringBuilder sSql = new StringBuilder();
			try
			{
				sSql.AppendLine("SELECT TRCODTER FROM TERCEROS WITH(NOLOCK) WHERE TRCODNIT =@p0");

				return Convert.ToInt32(ObjDB.ExecuteScalar(sSql.ToString(), TRCODNIT));
			}
			catch (Exception ex)
			{
				throw ex;
			}
			finally
			{
				sSql = null;
			}
		}

		public static int InsertTercero(DBAccess ObjDB, string TRCODEMP, int TRCODTER, string TRNOMBRE, string TRNOMBR2, string TRCONTAC, int? TRCODEDI,
										string TRCODNIT, string TRDIGVER, string TRDIRECC, string TRDIREC2, string TRDELEGA, string TRCOLONI, string TRNROTEL, string TRNROFAX,
										string TRPOSTAL, string TRCORREO, string TRCIUDAD, string TRCIUDA2, string TRCDPAIS, string TRMONEDA, string TRIDIOMA, string TRBODEGA,
										string TRTERPAG, string TRMODDES, string TRTERDES, string TRCATEGO, int? TRAGENTE, string TRLISPRE, string TRLISPRA, double? TRDESCUE,
										double? TRCUPOCR, string TRINDCLI, string TRINDPRO, string TRINDSOP, string TRINDEMP, string TRINDSOC, string TRINDVEN, string TRINDFOR, string TRCDCLA1,
										string TRCDCLA2, string TRCDCLA3, string TRCDCLA4, string TRCDCLA5, string TRCDCLA6, string TRDTTEC1, string TRDTTEC2, string TRDTTEC3,
										string TRDTTEC4, double? TRDTTEC5, double? TRDTTEC6, int? TRPROGDT, string TRESTADO, string TRCAUSAE, string TRNMUSER, string TROBSERV,
										DateTime? TRFECNAC, string TRRESPAL, double? TRRESCUP, string TRAPELLI, string TRNOMBR3, string TRTIPDOC, string TRDIGCHK,
										string TRCODZONA, string TRTIPREG, string TRGRANCT, string TRAUTORE, string TRNOMCOMERCIAL)
		{
			StringBuilder sSql = new StringBuilder();
			try
			{
				sSql.AppendLine("INSERT INTO TERCEROS (TRCODEMP,TRCODTER,TRNOMBRE,TRNOMBR2,TRCONTAC,TRCODEDI,TRCODNIT,TRDIGVER,TRDIRECC,TRDIREC2,TRDELEGA,TRCOLONI,TRNROTEL,");
				sSql.AppendLine("TRNROFAX,TRPOSTAL,TRCORREO,TRCIUDAD,TRCIUDA2,TRCDPAIS,TRMONEDA,TRIDIOMA,TRBODEGA,TRTERPAG,TRMODDES,TRTERDES,TRCATEGO,TRAGENTE,TRLISPRE,");
				sSql.AppendLine("TRLISPRA,TRDESCUE,TRCUPOCR,TRINDCLI,TRINDPRO,TRINDSOP,TRINDEMP,TRINDSOC,TRINDVEN,TRINDFOR,TRCDCLA1,TRCDCLA2,TRCDCLA3,TRCDCLA4,TRCDCLA5,TRCDCLA6,");
				sSql.AppendLine("TRDTTEC1,TRDTTEC2,TRDTTEC3,TRDTTEC4,TRDTTEC5,TRDTTEC6,TRPROGDT,TRESTADO,TRCAUSAE,TRNMUSER,TROBSERV,TRFECNAC,TRRESPAL,TRRESCUP,TRAPELLI,");
				sSql.AppendLine("TRNOMBR3,TRTIPDOC,TRDIGCHK,TRCODZONA,TRTIPREG,TRGRANCT,TRAUTORE,TRNOMCOMERCIAL,TRFECING,TRFECMOD) VALUES");
				sSql.AppendLine("(@p0,@p1,@p2,@p3,@p4,@p5,@p6,@p7,@p8,@p9,@p10,@p11,@p12,");
				sSql.AppendLine("@p13,@p14,@p15,@p16,@p17,@p18,@p19,@p20,@p21,@p22,@p23,@p24,@p25,@p26,@p27,");
				sSql.AppendLine("@p28,@p29,@p30,@p31,@p32,@p33,@p34,@p35,@p36,@p37,@p38,@p39,@p40,@p41,@p42,");
				sSql.AppendLine("@p43,@p44,@p45,@p46,@p47,@p48,@p49,@p50,@p51,@p52,@p53,@p54,@p55,@p56,@p57,");
				sSql.AppendLine("@p58,@p59,@p60,@p61,@p62,@p63,@p64,@p65,@p66,GETDATE(),GETDATE())");


				return ObjDB.ExecuteNonQuery(sSql.ToString(), TRCODEMP, TRCODTER, TRNOMBRE, TRNOMBR2, TRCONTAC, TRCODEDI, TRCODNIT, TRDIGVER, TRDIRECC, TRDIREC2, TRDELEGA, TRCOLONI, TRNROTEL,
				TRNROFAX, TRPOSTAL, TRCORREO, TRCIUDAD, TRCIUDA2, TRCDPAIS, TRMONEDA, TRIDIOMA, TRBODEGA, TRTERPAG, TRMODDES, TRTERDES, TRCATEGO, TRAGENTE, TRLISPRE,
				TRLISPRA, TRDESCUE, TRCUPOCR, TRINDCLI, TRINDPRO, TRINDSOP, TRINDEMP, TRINDSOC, TRINDVEN, TRINDFOR, TRCDCLA1, TRCDCLA2, TRCDCLA3, TRCDCLA4, TRCDCLA5, TRCDCLA6,
				TRDTTEC1, TRDTTEC2, TRDTTEC3, TRDTTEC4, TRDTTEC5, TRDTTEC6, TRPROGDT, TRESTADO, TRCAUSAE, TRNMUSER, TROBSERV, TRFECNAC, TRRESPAL, TRRESCUP, TRAPELLI,
				TRNOMBR3, TRTIPDOC, TRDIGCHK, TRCODZONA, TRTIPREG, TRGRANCT, TRAUTORE, TRNOMCOMERCIAL);
			}
			catch (Exception ex)
			{
				throw ex;
			}
			finally
			{
				sSql = null;
			}
		}
	}
}
